/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
  const ElNumber: typeof import('element-plus/es')['ElNumber']
  const ElNumberInput: typeof import('element-plus/es')['ElNumberInput']
}
