export const SERIES_SYMBOL = '__PS_SERIES__'
export const MERGE_SYMBOL = '__PS_MERGE__'
export const UNMOUNT_SYMBOL = '__PS_UNMOUNT__'
export const MODULE_SYMBOL = '__PS_MODULE__'
export const META_SYMBOL = '__PS_META__'
export const APP_SYMBOL = '__PS__'
