export {}
declare global {
  const Addon: typeof import('phecda-server')['Addon']
  const Arg: typeof import('phecda-server')['Arg']
  const Assign: typeof import('phecda-server')['Assign']
  const BadGatewayException: typeof import('phecda-server')['BadGatewayException']
  const BadRequestException: typeof import('phecda-server')['BadRequestException']
  const Base: typeof import('phecda-server')['Base']
  const Body: typeof import('phecda-server')['Body']
  const Clear: typeof import('phecda-server')['Clear']
  const ConflictException: typeof import('phecda-server')['ConflictException']
  const Controller: typeof import('phecda-server')['Controller']
  const Ctx: typeof import('phecda-server')['Ctx']
  const CustomResponse: typeof import('phecda-server')['CustomResponse']
  const Define: typeof import('phecda-server')['Define']
  const Delete: typeof import('phecda-server')['Delete']
  const ERROR_SYMBOL: typeof import('phecda-server')['ERROR_SYMBOL']
  const Effect: typeof import('phecda-server')['Effect']
  const Empty: typeof import('phecda-server')['Empty']
  const Err: typeof import('phecda-server')['Err']
  const Exception: typeof import('phecda-server')['Exception']
  const Expose: typeof import('phecda-server')['Expose']
  const Factory: typeof import('phecda-server')['Factory']
  const Filter: typeof import('phecda-server')['Filter']
  const ForbiddenException: typeof import('phecda-server')['ForbiddenException']
  const FrameworkException: typeof import('phecda-server')['FrameworkException']
  const Generator: typeof import('phecda-server')['Generator']
  const Get: typeof import('phecda-server')['Get']
  const Global: typeof import('phecda-server')['Global']
  const Guard: typeof import('phecda-server')['Guard']
  const HTTPGenerator: typeof import('phecda-server')['HTTPGenerator']
  const Head: typeof import('phecda-server')['Head']
  const Header: typeof import('phecda-server')['Header']
  const HttpBase: typeof import('phecda-server')['HttpBase']
  const If: typeof import('phecda-server')['If']
  const Init: typeof import('phecda-server')['Init']
  const Inject: typeof import('phecda-server')['Inject']
  const Injectable: typeof import('phecda-server')['Injectable']
  const InvalidInputException: typeof import('phecda-server')['InvalidInputException']
  const Isolate: typeof import('phecda-server')['Isolate']
  const ManyFiles: typeof import('phecda-server')['ManyFiles']
  const Mixin: typeof import('phecda-server')['Mixin']
  const NotFoundException: typeof import('phecda-server')['NotFoundException']
  const OneFile: typeof import('phecda-server')['OneFile']
  const PAddon: typeof import('phecda-server')['PAddon']
  const PExtension: typeof import('phecda-server')['PExtension']
  const PFilter: typeof import('phecda-server')['PFilter']
  const PGuard: typeof import('phecda-server')['PGuard']
  const PPipe: typeof import('phecda-server')['PPipe']
  const Param: typeof import('phecda-server')['Param']
  const Patch: typeof import('phecda-server')['Patch']
  const PayloadLargeException: typeof import('phecda-server')['PayloadLargeException']
  const Pipe: typeof import('phecda-server')['Pipe']
  const Pipeline: typeof import('phecda-server')['Pipeline']
  const Post: typeof import('phecda-server')['Post']
  const Provide: typeof import('phecda-server')['Provide']
  const Put: typeof import('phecda-server')['Put']
  const Query: typeof import('phecda-server')['Query']
  const Queue: typeof import('phecda-server')['Queue']
  const RPCGenerator: typeof import('phecda-server')['RPCGenerator']
  const Route: typeof import('phecda-server')['Route']
  const Rpc: typeof import('phecda-server')['Rpc']
  const RpcBase: typeof import('phecda-server')['RpcBase']
  const Search: typeof import('phecda-server')['Search']
  const ServerBase: typeof import('phecda-server')['ServerBase']
  const ServerPhecda: typeof import('phecda-server')['ServerPhecda']
  const ServiceUnavailableException: typeof import('phecda-server')['ServiceUnavailableException']
  const Storage: typeof import('phecda-server')['Storage']
  const Tag: typeof import('phecda-server')['Tag']
  const TestController: typeof import('./src/server/test.controller')['TestController']
  type TestController = InstanceType<typeof import('./src/server/test.controller')['TestController']>
  const TestService: typeof import('./src/server/test.service')['TestService']
  type TestService = InstanceType<typeof import('./src/server/test.service')['TestService']>
  const TimeoutException: typeof import('phecda-server')['TimeoutException']
  const TimerException: typeof import('phecda-server')['TimerException']
  const UnauthorizedException: typeof import('phecda-server')['UnauthorizedException']
  const UndefinedException: typeof import('phecda-server')['UndefinedException']
  const Unique: typeof import('phecda-server')['Unique']
  const Unmount: typeof import('phecda-server')['Unmount']
  const UnsupportedMediaTypeException: typeof import('phecda-server')['UnsupportedMediaTypeException']
  const User: typeof import('./src/server/test.controller')['User']
  const ValidateException: typeof import('phecda-server')['ValidateException']
  const Watcher: typeof import('phecda-server')['Watcher']
  const WorkerException: typeof import('phecda-server')['WorkerException']
  const addAddon: typeof import('phecda-server')['addAddon']
  const addDecoToClass: typeof import('phecda-server')['addDecoToClass']
  const addFilter: typeof import('phecda-server')['addFilter']
  const addGuard: typeof import('phecda-server')['addGuard']
  const addPipe: typeof import('phecda-server')['addPipe']
  const emitter: typeof import('phecda-server')['emitter']
  const getMergedMeta: typeof import('phecda-server')['getMergedMeta']
  const getMeta: typeof import('phecda-server')['getMeta']
  const getMetaKey: typeof import('phecda-server')['getMetaKey']
  const getMetaParams: typeof import('phecda-server')['getMetaParams']
  const getOwnMeta: typeof import('phecda-server')['getOwnMeta']
  const getOwnMetaKey: typeof import('phecda-server')['getOwnMetaKey']
  const getOwnMetaParams: typeof import('phecda-server')['getOwnMetaParams']
  const getTag: typeof import('phecda-server')['getTag']
  const isPhecda: typeof import('phecda-server')['isPhecda']
  const log: typeof import('phecda-server')['log']
  const phecdaNamespace: typeof import('phecda-server')['phecdaNamespace']
  const runMiddleware: typeof import('phecda-server')['runMiddleware']
  const setInject: typeof import('phecda-server')['setInject']
  const setLogger: typeof import('phecda-server')['setLogger']
  const setMeta: typeof import('phecda-server')['setMeta']
  const useS: typeof import('phecda-server')['useS']
  const wait: typeof import('phecda-server')['wait']
  const x: typeof import('./src/server/test.controller')['x']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { User, TestController } from './src/server/test.controller'
  import('./src/server/test.controller')
  // @ts-ignore
  export type { TestService } from './src/server/test.service'
  import('./src/server/test.service')
}